### ISSUE TITLE
Intro Slides

### ISSUE THREAD

**Issue by HerrLapsus** [dev-kitchen/icf-esther-book-droid#1]
- [ ] Bookcover (Welcome)
- [ ] Scanning Explanation
- [ ] Let's go

**Comment by SamuelKupferschmid** [comment]
Gemäss iOS App entwerfen:
![photo_2016-08-23_11-02-44](https://cloud.githubusercontent.com/assets/6099053/17886270/42148eb2-6921-11e6-8072-332ce2542692.jpg)
