### ISSUE TITLE
Home View

### ISSUE THREAD

**Issue by HerrLapsus** [dev-kitchen/icf-esther-book-droid#2]
- List of scanned contents
- Show arrow to scan button if list is empty
- Achievements
- Floating Action Button

**Comment by SamuelKupferschmid** [comment]
View folgendermassen anpassen:
- Anstelle von Thumbnails, quadratische Cards verwenden
- Nur Titel, keine Description
- Titel unten, zentriert platzieren. Overlay im unteren Bereich 
- FAB muss Zentriert sein und mit + Symbol
